### ISSUE TITLE
An error  Error in row.names(umi@assays$RNA@counts)

### ISSUE THREAD

**Issue by cystone** [bicciatolab/PoPsicleR#5]
seurat_obj <- PrePlots(sample_name = ii,
                         input_data = newDir,
                         percentage = 0.1, gene_filter = 200, 
                         cellranger = TRUE,
                         organism = "human",
                        out_folder = newDir)

Error in row.names(umi@assays$RNA@counts):
Error no slot of name "counts" for this object of class "Assay5"
====================
Maybe should edit the function plotGene:

as.data.frame(sce.all@assays$RNA@counts[1:10, 1:2])
to
as.data.frame(sce.all@assays$RNA@layers$counts[1:10, 1:2])
or
as.data.frame(sce.all@assays$RNA$counts[1:10, 1:2])

**Comment by matteomarchionni** [comment]
Thank you for your suggestion. We have updated the code to utilize the GetAssayData() function in the Seurat package instead of the previous slot call. We recommend using only the correct version of the Seurat and SeuratObject libraries, as we cannot guarantee full compatibility with other versions. Please refer to the installation instructions provided in our repository.
